version: '3'
services:
  database:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  main:
    container_name: population-statistics
    build:
      context: .
      args:
        env: prod
    depends_on:
      - database