selHouseWithPersonNum="""
SELECT `id`, `name`, `shopName`, `regId`, `address`, `lglName`, `lglId`, `lglPhone`, `createdAt`, `updatedAt`, (
  SELECT COUNT(`person`.`id`) FROM `people` AS `person` WHERE `person`.`lvAddress` = `company`.`address`
) AS `psnNum` FROM `companies` AS `company` WHERE `company`.`shopName` = ''
"""
selCompanyNum="""
SELECT COUNT(`id`) AS `cmpNum` FROM `companies` AS `company` WHERE `company`.`shopName` != ''
"""
selClosedCompanyNum="""
SELECT COUNT(`id`) AS `cmpNum` FROM `companies` AS `company` WHERE `company`.`shopName` != '' AND `company`.`isClosed` = TRUE
"""
selCompanyNumGpByType="""
SELECT `type`, COUNT(`id`) AS `cmpNum` FROM `companies` AS `company` WHERE `company`.`shopName` != '' GROUP BY `company`.`type`
"""
selFFPoiCompanyNum="""
SELECT COUNT(`id`) AS `cmpNumHasLiving` FROM `companies` AS `company` WHERE `company`.`hasLiving` = TRUE;
SELECT COUNT(`id`) AS `cmpNumAlgStreet` FROM `companies` AS `company` WHERE `company`.`isAlgStreet` = TRUE;
SELECT COUNT(`id`) AS `cmpNumHasStore` FROM `companies` AS `company` WHERE `company`.`hasStore` = TRUE;
SELECT COUNT(`id`) AS `cmpNumUseFire` FROM `companies` AS `company` WHERE `company`.`useFire` = TRUE;
SELECT COUNT(`id`) AS `cmpNumTopBtm` FROM `companies` AS `company` WHERE `company`.`isTopBottom` = TRUE
"""
selPersonNum="""
SELECT COUNT(`id`) AS `pplNum` FROM `people` AS `person`
"""
selHouseNum="""
SELECT COUNT(`id`) AS `hsNum` FROM `companies` AS `house` WHERE `house`.`shopName` = ''
"""