selHouseWithPersonNum="""
SELECT `id`, `name`, `shopName`, `regId`, `address`, `lglName`, `lglId`, `lglPhone`, `createdAt`, `updatedAt`, (
  SELECT COUNT(`person`.`id`) FROM `people` AS `person` WHERE `person`.`lvAddress` = `company`.`address`
) AS `psnNum` FROM `companies` AS `company` WHERE `company`.`shopName` = ''
"""
selCompanyNum="""
SELECT COUNT(`id`) AS `cmpNum` FROM `companies` AS `company` WHERE `company`.`shopName` != ''
"""
selCompanyNumGpByType="""
SELECT `type`, COUNT(`id`) AS `cmpNum` FROM `companies` AS `company` WHERE `company`.`shopName` != '' GROUP BY `company`.`type`
"""
selCompanyNumOpnNgt="""
SELECT COUNT(`id`) AS `cmpNum` FROM `companies` AS `company` WHERE `company`.`shopName` != '' AND CONVERT(SUBSTRING(`company`.`openHours`, -5, 2), UNSIGNED) > 21
"""
selPersonNum="""
SELECT COUNT(`id`) AS `pplNum` FROM `people` AS `person`
"""
selPersonNumGpByCompany="""
SELECT COUNT(`person`.`id`) AS `pplNum`, `company`.`shopName` FROM `people` AS `person`, `companies` AS `company` WHERE `company`.`shopName` != '' AND `person`.`cmpId` = `company`.`id` GROUP BY `company`.`shopName`
"""
selPersonNumGpByHouse="""
SELECT COUNT(`person`.`id`) AS `pplNum`, `house`.`address` FROM `people` AS `person`, `companies` AS `house` WHERE `house`.`shopName` = '' AND `person`.`lvAddress` = `house`.`address` GROUP BY `house`.`address`
"""
selPersonNumLvAndWk="""
SELECT COUNT(`person`.`id`) AS `pplNum` FROM `people` AS `person` WHERE `person`.`cmpId` IS NOT NULL AND `person`.`lvAddress` IN (SELECT `house`.`address` FROM `companies` AS `house`)
"""
selPersonNumGpByNation="""
SELECT COUNT(`person`.`id`) AS `pplNum`, `person`.`nation` FROM `people` AS `person` GROUP BY `person`.`nation`
"""
selHouseNum="""
SELECT COUNT(`id`) AS `hsNum` FROM `companies` AS `house` WHERE `house`.`shopName` = ''
"""